import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(),
})
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), issuer: text('issuer'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt'), updatedAt: timestamp('updatedAt') })
export const remoteDevices = pgTable('remote_devices', { id: text('id').primaryKey(), userId: text('userId').notNull(), name: text('name').notNull(), hostname: text('hostname').notNull(), os: text('os').notNull(), status: text('status').notNull(), pairingCode: text('pairingCode'), installTokenHash: text('installTokenHash'), installTokenExpiresAt: timestamp('installTokenExpiresAt'), enrollmentTokenHash: text('enrollmentTokenHash'), agentVersion: text('agentVersion').notNull(), lastSeenAt: timestamp('lastSeenAt'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull() })
export const remoteSessions = pgTable('remote_sessions', { id: text('id').primaryKey(), userId: text('userId').notNull(), deviceId: text('deviceId').notNull(), status: text('status').notNull(), startedAt: timestamp('startedAt').notNull(), endedAt: timestamp('endedAt'), createdAt: timestamp('createdAt').notNull() })
